Add controllers
SergKostarev/java-shareit pull request #1
Opened 2024-10-27 09:11 UTC by SergKostarev

2024-10-27 18:44 UTC, z8q requested changes

2024-10-27 18:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/User.java
>  package ru.practicum.shareit.user;
можно тоже переместить в пакет model

2024-10-27 18:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +@Validated
Valid должен сработать без Validated,
но если захотим добавить проверку например на аргумент метода
```JAVA
public UserDto getUserById(@PathVariable("id") @Positive Long id)
```
то Validated будет нужен

2024-10-27 18:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +        throw new NotFoundException("Вещь не найдена.", itemId);
Можно попробовать немного оптимизировать
```JAVA
return Optional.ofNullable(items.get(itemId))
        .map(item -> {
            log.debug("Получение вещи с идентификатором " + itemId);
            return item;
        })
        .orElseThrow(() -> {
            log.debug("Вещь с идентификатором " + itemId + " не найдена.");
            return new NotFoundException("Вещь не найдена.", itemId);
        });
```
map будет вызываться, если в Optional что-то есть
Если нет, то сразу перейдем в orElseThrow

2024-10-27 18:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +        throw new NotFoundException("Пользователь не найден.", id);
тут тоже можно попробовать применить map и orElseThrow методы у Optional

2024-10-27 18:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +    private static Long identifier = 0L;
Скорее всего нет необходимости делать поле статическим
но это больше пожелание,
когда будем добавлять базы, вопрос решится)

2024-10-28 09:30 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/user/User.java
>  package ru.practicum.shareit.user;
Исправил

2024-10-28 09:39 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +@Validated
Исправил

2024-10-28 09:39 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +        throw new NotFoundException("Вещь не найдена.", itemId);
Исправил

2024-10-28 09:39 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +        throw new NotFoundException("Пользователь не найден.", id);
Исправил

2024-10-28 09:39 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +    private static Long identifier = 0L;
Исправил

2024-10-28 19:41 UTC, z8q approved these changes

2024-11-04 07:45 UTC, merged