Add bookings
SergKostarev/java-shareit pull request #2
Opened 2024-11-14 06:42 UTC by SergKostarev

2024-11-14 19:35 UTC, z8q requested changes

2024-11-14 19:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
На дипломе будут рекомендовать не использовать data с сущностями, статьи про это
https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/
https://habr.com/ru/companies/haulmont/articles/564682/
https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/

Один из примеров возможных проблем

Data содержит в себе toString
Есть сущность с полем OneToMany Set<Items> items
У OneToMany по умолчанию параметр fetch == FetchType.LAZY
Это значит, что, если мы запросим из базы саму сущность, items не будут подгружены сразу, а только, если к полю будут обращения

Через аннотацию Data у нас появится созданный ломбоком toString(), и, если мы где-то его вызовем, то будет обращение к items, и могут возникать дополнительные обращения к базе
Если такие обращения будут при уже закрытой сессии хибернейта, то можем получить LazyInitializationException

2024-11-14 19:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +                .orElseThrow(() -> new NotFoundException("Вещь не найдена.", itemId));
тут все таки код начинает походить на сервисные блоки, лучше перенести в сервис

2024-11-14 19:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userRepository.getUserById(userId);
вот здесь как понял, происходит check на существование пользователя
лучше это реализовать в userService
В логике сервиса формируется определенное сообщение,  возможно исключение
В логике репозитория лучше держать только сам запрос, который реализуется либо через название метода, либо через аннотацию Query, либо через dsl (но сам dsl лучше тоже формировать в сервисе)

2024-11-16 07:32 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Спасибо.
Оставил только @Getter и @Setter, переопределил equals() и hashCode().

2024-11-16 07:32 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +                .orElseThrow(() -> new NotFoundException("Вещь не найдена.", itemId));
Исправил

2024-11-16 07:32 UTC, SergKostarev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userRepository.getUserById(userId);
Исправил

2024-11-17 06:40 UTC, z8q approved these changes

2024-11-22 17:58 UTC, merged